import { promises as fsp } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { idOf, windowsEntries } from '../../src/main/launcher/catalog.js'
import {
  APPS_FOLDER,
  isPackagedAppId,
  packagedAppIdOf,
  parseShellView,
  readWindowsShell,
  type WindowsShellView,
} from '../../src/main/launcher/windows-apps.js'
import { extractWindowsIcons } from '../../src/main/launcher/windows-icons.js'

const b64 = (text: string): string => Buffer.from(text, 'utf8').toString('base64')
const TEAMS = 'MSTeams_8wekyb3d8bbwe!MSTeams'

describe('packaged app ids', () => {
  it('accepts the ids the Start Menu lists packaged apps by', () => {
    for (const id of [
      TEAMS,
      'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App',
      'excel.cloud.microsoft-681E9612_tw870azjyp97t!App',
      'PythonSoftwareFoundation.PythonManager_3847v3x7pw1km!Py.Manager.Exe',
      'windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel',
    ]) {
      expect(isPackagedAppId(id), id).toBe(true)
    }
  })

  it('refuses shortcut-backed ids, special folders and anything that could carry more', () => {
    for (const id of [
      '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\cmd.exe',
      'Microsoft.AutoGenerated.{97880E4E-9653-3DA7-99DC-D2454E1F6F2E}',
      'Microsoft.Windows.Explorer',
      'https://nodejs.org/',
      'Foo_8wekyb3d8bbwe!App other',
      'Foo_8wekyb3d8bbwe!App"',
      'Foo_8wekyb3d8bbwe!App\\..\\x',
      '..\\Foo_8wekyb3d8bbwe!App',
      'Foo_8WEKYB3D8BBWE!App',
      'Foo_8wekyb3d8bbwe!',
      '',
    ]) {
      expect(isPackagedAppId(id), id).toBe(false)
    }
  })

  it('reads a packaged app only from a shell:AppsFolder target', () => {
    expect(packagedAppIdOf(`${APPS_FOLDER}${TEAMS}`)).toBe(TEAMS)
    expect(packagedAppIdOf(TEAMS)).toBeNull()
    expect(packagedAppIdOf(`${APPS_FOLDER}Microsoft.Windows.Explorer`)).toBeNull()
    expect(packagedAppIdOf('C:\\Programs\\Teams.lnk')).toBeNull()
  })
})

describe('parseShellView', () => {
  it('reads names in order and the packaged apps', () => {
    const out = [
      `n ${b64('コマンド プロンプト')}`,
      'n -',
      `a ${b64('Microsoft Teams')} ${b64(TEAMS)}`,
      '',
    ].join('\r\n')
    expect(parseShellView(out, 2)).toEqual({
      names: ['コマンド プロンプト', null],
      apps: [{ name: 'Microsoft Teams', appId: TEAMS }],
    })
  })

  it('drops apps that are not packaged, have no name or are not base64', () => {
    const out = [
      `a ${b64('Command Prompt')} ${b64('{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\cmd.exe')}`,
      `a ${b64('  ')} ${b64(TEAMS)}`,
      `a %%% ${b64(TEAMS)}`,
      `a ${b64('Teams')}`,
      'warning: something',
    ].join('\n')
    expect(parseShellView(out, 0)).toEqual({ names: [], apps: [] })
  })

  it('gives no names when their count does not match the paths, but keeps the apps', () => {
    const out = [`n ${b64('A')}`, `a ${b64('Teams')} ${b64(TEAMS)}`].join('\n')
    expect(parseShellView(out, 2)).toEqual({
      names: [null, null],
      apps: [{ name: 'Teams', appId: TEAMS }],
    })
  })
})

describe('readWindowsShell', () => {
  it('passes the paths on stdin, never in the script', async () => {
    const run = vi.fn(async (_script: string, input: string) =>
      input
        .split('\n')
        .filter(Boolean)
        .map((line) => `n ${line}`)
        .join('\n'),
    )
    const view = await readWindowsShell(['C:\\a b\\x.lnk', 'C:\\日本\\y.lnk'], run)
    expect(view.names).toEqual(['C:\\a b\\x.lnk', 'C:\\日本\\y.lnk'])
    expect(run.mock.calls[0]?.[0]).not.toContain('x.lnk')
  })
})

describe('windowsEntries', () => {
  let root: string
  let userRoot: string

  beforeEach(async () => {
    const base = await fsp.mkdtemp(path.join(os.tmpdir(), 'elecdex-startmenu-'))
    root = path.join(base, 'all')
    userRoot = path.join(base, 'user')
    await fsp.mkdir(path.join(root, 'System Tools', 'Deep'), { recursive: true })
    await fsp.mkdir(userRoot, { recursive: true })
    await fsp.writeFile(path.join(root, 'System Tools', 'Command Prompt.lnk'), '')
    await fsp.writeFile(path.join(root, 'System Tools', 'Deep', 'Run.lnk'), '')
    await fsp.writeFile(path.join(root, 'System Tools', 'Uninstall Foo.lnk'), '')
    await fsp.writeFile(path.join(userRoot, 'Code.lnk'), '')
  })

  afterEach(async () => {
    await fsp.rm(path.dirname(root), { recursive: true, force: true })
  })

  const localized: Record<string, string> = {
    'Command Prompt.lnk': 'コマンド プロンプト',
    'Run.lnk': 'ファイル名を指定して実行',
    'System Tools': 'Windows システム ツール',
  }

  const fakeShell =
    (apps: WindowsShellView['apps']) =>
    async (paths: readonly string[]): Promise<WindowsShellView> => ({
      names: paths.map((p) => localized[path.basename(p)] ?? null),
      apps,
    })

  it('lists the packaged apps that have no shortcut, beside the shortcuts of both folders', async () => {
    const entries = await windowsEntries(
      [root, userRoot],
      fakeShell([{ name: 'Microsoft Teams', appId: TEAMS }]),
    )
    const teams = entries.find((e) => e.name === 'Microsoft Teams')
    expect(teams).toEqual({
      id: idOf('system', `${APPS_FOLDER}${TEAMS}`),
      name: 'Microsoft Teams',
      group: null,
      source: 'system',
      target: `${APPS_FOLDER}${TEAMS}`,
      args: [],
    })
    expect(entries.map((e) => e.name).sort()).toEqual(
      ['Code', 'Microsoft Teams', 'コマンド プロンプト', 'ファイル名を指定して実行'].sort(),
    )
  })

  it('names shortcuts and their groups as the Start Menu does, keeping ids by file', async () => {
    const entries = await windowsEntries([root, userRoot], fakeShell([]))
    const cmd = path.join(root, 'System Tools', 'Command Prompt.lnk')
    expect(entries.find((e) => e.target === cmd)).toMatchObject({
      id: idOf('system', cmd),
      name: 'コマンド プロンプト',
      group: 'Windows システム ツール',
    })
    expect(entries.find((e) => e.name === 'ファイル名を指定して実行')?.group).toBe(
      'Windows システム ツール',
    )
    expect(entries.find((e) => e.name === 'Code')?.group).toBeNull()
  })

  it('leaves out an uninstaller by its file name, whatever the shell calls it', async () => {
    const entries = await windowsEntries([root], async (paths) => ({
      names: paths.map(() => 'Something harmless'),
      apps: [],
    }))
    expect(entries.some((e) => e.target.includes('Uninstall'))).toBe(false)
  })

  it('falls back to file names and no packaged apps when PowerShell fails', async () => {
    const entries = await windowsEntries([root, userRoot], async () => {
      throw new Error('PowerShell blocked')
    })
    expect(entries.map((e) => [e.name, e.group]).sort()).toEqual(
      [
        ['Code', null],
        ['Command Prompt', 'System Tools'],
        ['Run', 'System Tools'],
      ].sort(),
    )
  })

  it('lists nothing from folders that do not exist', async () => {
    const read = vi.fn(fakeShell([]))
    expect(await windowsEntries([path.join(root, 'missing')], read)).toEqual([])
  })
})

describe.runIf(process.platform === 'win32')('the Windows shell (real PowerShell)', () => {
  const system32 = path.win32.join(process.env.SystemRoot ?? 'C:\\Windows', 'System32')

  it('names files, and lists packaged apps whose icons it can draw', async () => {
    const view = await readWindowsShell([
      path.win32.join(system32, 'taskmgr.exe'),
      path.win32.join(system32, 'no-such-program.exe'),
    ])
    expect(view.names[0]).toMatch(/\S/)
    expect(view.names[1]).toBeNull()
    for (const app of view.apps) expect(isPackagedAppId(app.appId)).toBe(true)
    const first = view.apps[0]
    // A server image may have no packaged apps at all.
    if (first === undefined) return
    const [icon] = await extractWindowsIcons([`${APPS_FOLDER}${first.appId}`])
    expect(icon).toMatch(/^data:image\/png;base64,iVBORw0KGgo/)
  }, 30_000)
})
